// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpFdAVY0Tdi5o1n4-HHIzRW5oM6VcB_X0',
    appId: '1:544024326479:web:e8dcd01d5422c7661dd53a',
    messagingSenderId: '544024326479',
    projectId: 'firs-form-project',
    authDomain: 'firs-form-project.firebaseapp.com',
    storageBucket: 'firs-form-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKye7pl5-PkDt_MW-CQEUVxHz8IwU6vkI',
    appId: '1:544024326479:android:9f283bf77914fc791dd53a',
    messagingSenderId: '544024326479',
    projectId: 'firs-form-project',
    storageBucket: 'firs-form-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIYdZ_7Y2rCq9cHFF_E_TItQdDdYlHlVU',
    appId: '1:544024326479:ios:b824023fc78a24941dd53a',
    messagingSenderId: '544024326479',
    projectId: 'firs-form-project',
    storageBucket: 'firs-form-project.firebasestorage.app',
    iosBundleId: 'com.example.firsMiniProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIYdZ_7Y2rCq9cHFF_E_TItQdDdYlHlVU',
    appId: '1:544024326479:ios:b824023fc78a24941dd53a',
    messagingSenderId: '544024326479',
    projectId: 'firs-form-project',
    storageBucket: 'firs-form-project.firebasestorage.app',
    iosBundleId: 'com.example.firsMiniProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpFdAVY0Tdi5o1n4-HHIzRW5oM6VcB_X0',
    appId: '1:544024326479:web:8a9ec965de27d22e1dd53a',
    messagingSenderId: '544024326479',
    projectId: 'firs-form-project',
    authDomain: 'firs-form-project.firebaseapp.com',
    storageBucket: 'firs-form-project.firebasestorage.app',
  );
}
